### ISSUE TITLE
Create a theme

### ISSUE THREAD

**Issue by AlbertoPdRF** [MLH-Fellowship/Fellowship-Companion#15]
I thought that our theme could be based on the Fellowship logo, how does that sound?

Also, should we offer a dark theme too?

**Comment by LakshyaKhatri** [comment]
As far the UI is simple to use, we can do anything we want! Just make sure that we won't get stuck in UI part in the middle (while making it look too great)

**Comment by AlbertoPdRF** [comment]
That won't be a problem, setting up a theme with Material-UI is pretty straightforward! 🙂

**Comment by LakshyaKhatri** [comment]
Okay then, we can do it. :smile:
