### ISSUE TITLE
Create Models for Timeline

### ISSUE THREAD

**Issue by LakshyaKhatri** [MLH-Fellowship/Fellowship-Companion#30]
Right now I have these models in my mind:
 - [ ] Issues
 - [ ] Pull Requests

**Comment by SaurabhAgarwala** [comment]
What about Code Reviews?

**Comment by LakshyaKhatri** [comment]
I am making it modular, we can add more things gradually.

**Comment by SaurabhAgarwala** [comment]
Ok, that sounds good as well
