### ISSUE TITLE
Figure out a way to run the server remotely

### ISSUE THREAD

**Issue by SaurabhAgarwala** [MLH-Fellowship/Fellowship-Companion#32]
Options under evaluation:
 - ngrok
 - Deploying the server on cloud

**Comment by SaurabhAgarwala** [comment]
Nopes not closed yet, we will go for deployment. Hence that has to be done. Awaiting @wrussell1999 to give us the credits so that we can proceed

**Comment by wrussell1999** [comment]
> Nopes not closed yet, we will go for deployment. Hence that has to be done. Awaiting @wrussell1999 to give us the credits so that we can proceed
> 

Should have credit now! If you need anymore, ping me on Discord!

**Comment by SaurabhAgarwala** [comment]
Done. The backend is hosted at [http://34.69.147.19:8000](http://34.69.147.19:8000). All the configuration done in the server itself
