### ISSUE TITLE
Create contributions page

### ISSUE THREAD

**Issue by LakshyaKhatri** [MLH-Fellowship/Fellowship-Companion#52]
One idea is to keep it similar to Github's timeline (and tweaking a few things according to need):
![Screenshot from 2020-07-15 14-05-21](https://user-images.githubusercontent.com/28972442/87523325-6d5d7900-c6a4-11ea-8da5-9b07f93ee834.png)

**Comment by AlbertoPdRF** [comment]
Yep, that's kind of what I had in mind! As soon as I can have a sample JSON I'll start coming up with something.

**Comment by LakshyaKhatri** [comment]
Alright! I have to be quick, I guess! There's a lot of work. :face_with_head_bandage:
